# This is a basic workflow to help you get started with Actions

name: build docker image

on:
  push:
    branches:
      - main
jobs:

  build-centos7-base-image:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          tags: italiangrid/centos7-base:latest
          context: ./centos7-base
          file: ./centos7-base/Dockerfile
          push: false

      - name: Push docker image
        run: docker push italiangrid/centos7-base:latest
